# Generated by Django 2.2.1 on 2020-06-26 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_category', models.CharField(max_length=20)),
                ('e_name', models.CharField(max_length=20)),
                ('e_description', models.TextField(max_length=20)),
                ('e_recommend_count', models.IntegerField(default=0)),
                ('e_created_at', models.DateTimeField(auto_now_add=True)),
                ('e_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_joined_at', models.DateTimeField(auto_now_add=True)),
                ('u_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('u_email', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
