# Generated by Django 2.2.1 on 2020-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='u_isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
