# Generated by Django 2.2 on 2020-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_u_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='e_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='exercise'),
        ),
    ]
