# Generated by Django 2.2 on 2020-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_magazine_m_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.CharField(max_length=20)),
                ('m_content', models.TextField()),
                ('m_created_at', models.DateTimeField(auto_now_add=True)),
                ('m_modified_at', models.DateTimeField(auto_now=True)),
                ('m_thumbnail', models.ImageField(blank=True, null=True, upload_to='diet')),
            ],
        ),
    ]
