# Generated by Django 2.2 on 2020-06-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='tdl_date',
            field=models.DateField(default='2020-06-28'),
            preserve_default=False,
        ),
    ]
